In [1]:
import json
import csv
import pandas as pd
import datetime

In [2]:
df = pd.read_json("AMA_merged.json")
df

,nickname,wxid,Local_id,Local_type,Timestamp,Text
0,25 技科 梁建輝,wxid_bk2z2t2ychyn22,2,1,2025-09-04 03:52:12,👀
1,25 匡院 苏涵瑜,wxid_9hpjr3hpy6th22,3,1,2025-09-04 03:52:17,👀
2,25 技科 梁建輝,wxid_bk2z2t2ychyn22,5,1,2025-09-04 03:52:28,你不乘噢
3,依鸣,wxid_g7u000tjc91t22,6,1,2025-09-04 03:52:50,👀
4,25 技科 倪睿萱,wxid_mugbf0fhylqf22,8,1,2025-09-04 03:53:07,👀
...,...,...,...,...,...,...
27143,依鸣,wxid_g7u000tjc91t22,1850,47,2025-10-13 01:59:58,[表情包]
27144,依鸣,wxid_g7u000tjc91t22,1851,47,2025-10-13 02:00:06,[表情包]
27145,依鸣,wxid_g7u000tjc91t22,1852,47,2025-10-13 02:00:13,[表情包]
27146,依鸣,wxid_g7u000tjc91t22,1853,47,2025-10-13 02:03:03,[表情包]
27147,依鸣,wxid_g7u000tjc91t22,1854,47,2025-10-13 02:03:42,[表情包]

In [3]:
filtered_df = df[df['Local_type'] == 1]
filtered_df

,nickname,wxid,Local_id,Local_type,Timestamp,Text
0,25 技科 梁建輝,wxid_bk2z2t2ychyn22,2,1,2025-09-04 03:52:12,👀
1,25 匡院 苏涵瑜,wxid_9hpjr3hpy6th22,3,1,2025-09-04 03:52:17,👀
2,25 技科 梁建輝,wxid_bk2z2t2ychyn22,5,1,2025-09-04 03:52:28,你不乘噢
3,依鸣,wxid_g7u000tjc91t22,6,1,2025-09-04 03:52:50,👀
4,25 技科 倪睿萱,wxid_mugbf0fhylqf22,8,1,2025-09-04 03:53:07,👀
...,...,...,...,...,...,...
27136,25 技科 倪睿萱,wxid_mugbf0fhylqf22,1840,1,2025-10-13 01:59:14,我在寝室刷文档都能沉沉睡去
27137,25 技科 倪睿萱,wxid_mugbf0fhylqf22,1841,1,2025-10-13 01:59:16,是的
27138,25 技科 倪睿萱,wxid_mugbf0fhylqf22,1842,1,2025-10-13 01:59:26,6:45集合
27140,圆锥曲线,wxid_m76swlb22bn132,1844,1,2025-10-13 01:59:35,全体吗
27142,25 技科 倪睿萱,wxid_mugbf0fhylqf22,1847,1,2025-10-13 01:59:45,是的

In [4]:
clean_df = df[["wxid", "Timestamp", "Text"]]
clean_df

                      wxid           Timestamp   Text
0      wxid_bk2z2t2ychyn22 2025-09-04 03:52:12      👀
1      wxid_9hpjr3hpy6th22 2025-09-04 03:52:17      👀
2      wxid_bk2z2t2ychyn22 2025-09-04 03:52:28   你不乘噢
3      wxid_g7u000tjc91t22 2025-09-04 03:52:50      👀
4      wxid_mugbf0fhylqf22 2025-09-04 03:53:07      👀
...                    ...                 ...    ...
27143  wxid_g7u000tjc91t22 2025-10-13 01:59:58  [表情包]
27144  wxid_g7u000tjc91t22 2025-10-13 02:00:06  [表情包]
27145  wxid_g7u000tjc91t22 2025-10-13 02:00:13  [表情包]
27146  wxid_g7u000tjc91t22 2025-10-13 02:03:03  [表情包]
27147  wxid_g7u000tjc91t22 2025-10-13 02:03:42  [表情包]

[27148 rows x 3 columns]

In [5]:
first_266df = clean_df.head(266)
first_266df

,wxid,Timestamp,Text
0,wxid_bk2z2t2ychyn22,2025-09-04 03:52:12,👀
1,wxid_9hpjr3hpy6th22,2025-09-04 03:52:17,👀
2,wxid_bk2z2t2ychyn22,2025-09-04 03:52:28,你不乘噢
3,wxid_g7u000tjc91t22,2025-09-04 03:52:50,👀
4,wxid_mugbf0fhylqf22,2025-09-04 03:53:07,👀
...,...,...,...
261,wxid_w5cck44ymfhi22,2025-09-04 08:49:51,251870
262,wxid_1vaqhsp5n5hs22,2025-09-04 08:51:13,870是工试
263,wxid_mugbf0fhylqf22,2025-09-04 08:52:47,捞捞我的issue
264,wxid_mugbf0fhylqf22,2025-09-04 08:53:00,https://nova.yuque.com/ph25ri/ygqsv9/ihxqr4ol8...
265,wxid_1vaqhsp5n5hs22,2025-09-04 08:53:27,可以拼团

In [7]:
# 6️⃣ 保存结果
clean_df.to_csv("ama_message.csv", index=False, encoding="utf-8-sig")

print(f"✅ 已成功提取 {len(clean_df)} 条有效消息。")
print("🎉 输出文件: ama_done.csv")
print(clean_df.head(10))

✅ 已成功提取 27148 条有效消息。
🎉 输出文件: ama_done.csv
                  wxid           Timestamp               Text
0  wxid_bk2z2t2ychyn22 2025-09-04 03:52:12                  👀
1  wxid_9hpjr3hpy6th22 2025-09-04 03:52:17                  👀
2  wxid_bk2z2t2ychyn22 2025-09-04 03:52:28               你不乘噢
3  wxid_g7u000tjc91t22 2025-09-04 03:52:50                  👀
4  wxid_mugbf0fhylqf22 2025-09-04 03:53:07                  👀
5  wxid_ribvfadnmikw22 2025-09-04 03:53:07       之前在食堂偶遇的[捂脸]
6  wxid_ribvfadnmikw22 2025-09-04 03:53:20  @25 匡院 苏涵瑜 我在你右前方
7  wxid_1vaqhsp5n5hs22 2025-09-04 03:53:21            在会议上回忆吗
8  wxid_mugbf0fhylqf22 2025-09-04 03:53:21             你上课不乘噢
9  wxid_dkg4wum8hbxe22 2025-09-04 03:53:23               xm社牛